services:
  market-app:
    build: .
    restart: unless-stopped
    environment:
      - SPRING_R2DBC_URL=r2dbc:postgresql://postgres:5432/ya_market
      - SPRING_JDBC_URL=jdbc:postgresql://postgres:5432/ya_market
      - SPRING_DBC_USERNAME=root
      - SPRING_DBC_PASSWORD=root
      - ENABLE_DEBUG=${ENABLE_DEBUG:-false}
    ports:
      - "8080:8080"
      - "8000:8000"
    networks:
      - ftmpt-market
    depends_on:
      - postgres

  postgres:
    image: postgres:16.11-alpine3.22
    restart: unless-stopped
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: ya_market
    ports:
      - "5433:5432"
    volumes:
      - ./db_data:/var/lib/postgresql/data
    networks:
      - ftmpt-market

networks:
  ftmpt-market:
    driver: bridge
