spring:
  application:
    name: my-market-app

  r2dbc:
    url: r2dbc:postgresql://localhost:5433/ya_market
    username: root
    password: root

  liquibase:
    # db connection
    url: jdbc:postgresql://localhost:5433/ya_market
    user: ${spring.r2dbc.username}
    password: ${spring.r2dbc.password}
    # main settings
    change-log: classpath:db/changelog/db.changelog-master.xml
    drop-first: true
    enabled: true

items:
  view:
    table.size: 3

---
spring:
  config:
    activate:
      on-profile: debug

logging:
  level:
    edu.yandex.project: DEBUG

    org.springframework.web: DEBUG
    org.springframework.web.servlet.DispatcherServlet: DEBUG
    org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter: DEBUG
    org.springframework.web.servlet.view.RedirectView: DEBUG

    org.springframework.r2dbc.core: DEBUG
    io.r2dbc.postgresql.PARAM: DEBUG
    io.r2dbc.postgresql.QUERY: DEBUG
